# Generated by Django 4.2.6 on 2023-12-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
