# Generated by Django 4.2.6 on 2023-12-31 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_remove_patient_insurance3_and_more'),
        ('insurance', '0003_insurance2_insurance3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insurance3',
        ),
    ]
