# Generated by Django 4.2.6 on 2023-12-18 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatment', '0006_alter_treatment_partinsurance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentamount', models.IntegerField(blank=True, null=True)),
                ('partinsurance', models.IntegerField()),
                ('partinsurance2', models.IntegerField(blank=True, null=True)),
                ('partinsurance3', models.IntegerField(blank=True, null=True)),
                ('partpatient', models.IntegerField()),
                ('amountpaid', models.IntegerField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('treatment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='treatment.treatment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_on'],
            },
        ),
    ]
