# Generated by Django 4.2.6 on 2023-12-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='registered_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
