# Generated by Django 4.2.6 on 2024-01-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='partinsurance3',
        ),
    ]
