# Generated by Django 4.2.6 on 2023-12-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_remove_intervention_id_alter_intervention_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
