# Generated by Django 4.2.6 on 2023-12-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0004_alter_treatment_registered_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='partinsurance2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='partinsurance3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
