# Generated by Django 4.2.6 on 2023-12-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0005_treatment_partinsurance2_treatment_partinsurance3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='partinsurance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='partinsurance2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='partinsurance3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='partpatient',
            field=models.IntegerField(),
        ),
    ]
