# Generated by Django 4.2.6 on 2023-12-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0006_alter_treatment_partinsurance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('registered_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'InterventionInsurance',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='partinsurance3',
        ),
    ]
