# Generated by Django 4.2.6 on 2023-12-31 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_delete_insurance3'),
        ('treatment', '0007_interventioninsurance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterventionInsurance',
        ),
        migrations.AddField(
            model_name='treatment',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.insurance'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='insurance2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.insurance2'),
        ),
    ]
