# Generated by Django 4.2.6 on 2024-01-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0008_delete_interventioninsurance_treatment_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
