# Generated by Django 4.2.6 on 2023-12-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_patient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance_pourcentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
