# Generated by Django 4.2.6 on 2023-12-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_patient_insurance_pourcentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance2',
            field=models.CharField(blank=True, null=True),
        ),
    ]
