# Generated by Django 4.2.6 on 2023-12-17 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_insurance2_insurance3'),
        ('patient', '0008_patient_insurance2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.insurance3'),
        ),
    ]
