# Generated by Django 4.2.6 on 2023-12-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_patient_insurance3_alter_patient_insurance2'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance2_matricule',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance2_pourcentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance3_matricule',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance3_pourcentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
