# Generated by Django 4.2.6 on 2023-12-17 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_patient_insurance2_matricule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='insurance3_pourcentage',
            new_name='pourcentage_insurance3',
        ),
    ]
