# Generated by Django 4.2.6 on 2023-12-17 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_rename_insurance3_pourcentage_patient_pourcentage_insurance3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='pourcentage_insurance3',
            new_name='insurance3_pourcentage',
        ),
    ]
