# Generated by Django 4.2.6 on 2023-12-31 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_rename_pourcentage_insurance3_patient_insurance3_pourcentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='insurance3',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance3_pourcentage',
        ),
    ]
