# Generated by Django 4.2.6 on 2024-01-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_remove_patient_insurance3_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance3_matricule',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
