# Generated by Django 4.2.6 on 2024-01-05 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_patient_insurance3_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='insurance3_matricule',
        ),
    ]
